version: "3.8"

services:
  bot:
    image: stealthninja1o1/characterdiscordbot:latest
    container_name: characterdiscordbot
    restart: unless-stopped
    command: ["npm", "run", "start"]
    environment:
      - CONFIG_PATH=/home/node/app/config.toml
    volumes:
      - ./config.toml:/home/node/app/config.toml
      - ./character.json:/home/node/app/character.json
      - ./workflow.json:/home/node/app/workflow.json
