services:
  bot:
    image: stealthninja1o1/characterdiscordbot:latest
    container_name: characterdiscordbot
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config.toml
    volumes:
      - ./config.toml:/app/config.toml
      - ./character.json:/app/character.json
      - ./chatMemory.json:/app/chatMemory.json
      - ./command_metadata.json:/app/command_metadata.json
      - ./workflow.json:/app/workflow.json